// Hao-Tien Cheng
// Endless Runner: Froggy Dash
// About 38 hours

// I think the tongue mechanic is interesting, and I am pretty proud of the way I implement it. 
// In play.js, I use a line generated by phaser to represent the tongue, 
// and add a physics sprite in a shape of circle that sticked at the end of the line to be the tonguetip. 
// I use loops with several phaser delaycall events to edit the length of the tongue to make a firing animation. 
// I looked up some examples from the professor to learn how phaser arcade physics work, 
// the documentation from phaser webpage to learn how to draw lines, and also used some mechanics from the previous assignments. 

// I edited the music and delete the part of repetition to make it sound more relaxing and delightful than the original version. 
// As for the art, I drew most of the background and assets of the game in a cartoonish style. I am proud of these personalized adjustments.
// I think a clever function that makes the game more interesting and challenging is that the frog can aim to eat flies during its jump. 
// This increases the difficulty of control and challenges players to make demands quickly and accurately.


let config = {
    type: Phaser.AUTO,
    width: 1120,
    height: 720,
    physics: {
        default: 'arcade',
        arcade: {
            debug: true,
            gravity: {
                x: 0,
                y: 0
            }
        }
    },
    scene: [Menu, Play, GameOver]
}

let game = new Phaser.Game(config)

// Set UI size
let borderUISize = game.config.height / 15
let borderPadding = borderUISize / 3

// keys
let keyR, keyM, keySPACE
let mouseX, mouseY, cursors

// tile size
const tileSize = 35